version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "4000:8080"
    volumes:
      - ./src:/home/node/app/src
      - ./data:/home/node/app/data
      - ./uploads:/home/node/app/uploads
    container_name: eiem-api
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
    depends_on: 
      - mysql
    

  mysql:
    container_name: eiem-db
    image: mysql:5.7
    command: --init-file /init.sql
    volumes:
      - ./init.sql:/init.sql
      - mysql:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    restart: "on-failure"

volumes:
  mysql: